### ISSUE TITLE
Toolbox not updating on toolboxCategories change

### ISSUE THREAD

**Issue by hauckwill** [patientslikeme/react-blockly-component#17]
If this is actually working, an example would be much appreciated.

**Comment by nbudin** [comment]
Hey @hauckwill!  Sorry about this - I won't be able to look until after the (long, in the US) weekend.  I'll have a look on Tuesday.  If anyone else is able to look faster and has some ideas about why this is happening, I'd appreciate it.

**Comment by hauckwill** [comment]
Really appreciate it, thanks!

**Comment by nbudin** [comment]
OK, sorry for the delay in getting to this - this was a bug (actually, I'm not sure how this was supposed to work to begin with), and is now fixed in version 3.0.1, which I'm releasing now.
