### ISSUE TITLE
bug in the BlocklyEditor.jsx componentDidUpdate

### ISSUE THREAD

**Issue by prabak** [patientslikeme/react-blockly-component#18]
Hi,

I belieev the line `!Immutable.fromJS(this.props.toolboxCategories).equals(Immutable.fromJS(prevProps.toolboxBlocks))`
should be
`!Immutable.fromJS(this.props.toolboxCategories).equals(Immutable.fromJS(prevProps.toolboxCategories))`.

If I understand the code correctly, in `componentDidUpdate()`, you want to check if either toolboxBlocks or toolboxCategories changed.

thanks

**Comment by nbudin** [comment]
Thanks for the bug report, @prabak!  This is now fixed in version 3.0.2.
