### ISSUE TITLE
Error in BlocklyEditor.jsx

### ISSUE THREAD

**Issue by ceemoo91** [patientslikeme/react-blockly-component#20]
Hello i think there is an error in the BlocklyEditor.jsx-File on line 22.
Categories do not have a type, but it is required in the sourcecode.

```javascript
const categoryPropsNonRecursive = {
  type: PropTypes.string.isRequired,
  name: PropTypes.string,
  custom: PropTypes.string,
  colour: PropTypes.string,
  blocks: PropTypes.arrayOf(BlockPropType),
};
```

This is the warning wich comes up:
```
Warning: Failed prop type: The prop `toolboxCategories[0].type` is marked as required in `BlocklyEditor`, but its value is `undefined`.
    in BlocklyEditor (created by TestEditor)
    in TestEditor

**Comment by japonophile** [comment]
Experiencing the same issue.  Do you have a workaround for this?

**Comment by nbudin** [comment]
Hi folks!  Things at work have been incredibly busy the last few weeks and I don't anticipate having time to work on this in the near future, but if one of you has time to make a pull request to fix this (probably just by making that one propType not required), I would be glad to review and/or do a release.

**Comment by ceemoo91** [comment]
i have simply remove the line `type: PropTypes.string.isRequired,` because a category does not have a type.

**Comment by nbudin** [comment]
Version 3.0.3 is now released, which leaves the `type` prop in place but makes it optional.
