### ISSUE TITLE
Example of how to load ToolboxXml and Library.xml generated by Blockly Developer Tools

### ISSUE THREAD

**Issue by Macilias** [patientslikeme/react-blockly-component#25]
I wonder how to feed the toolboxCategories based on the toolbox.xml generated by Blockly Developer Tools.
The component variable toolboxCategories expects an JS array but the output of Blockly Developer Tools is an xml file.
I tried:
```
componentDidMount() {
    window.setTimeout(() => {
      const toolboxXml = Blockly.Xml.textToDom(ConfigFiles.ToolboxXML);
      this.setState({
        toolboxCategories: toolboxXml
      });
    }, 100);
  }
```
but had no luck ending with:
```
Uncaught TypeError: this.props.categories.map is not a function
```
Exception

Update:
As far as the documentation of Blockly goes, the toolbox.xml should be directly injected into Blockly:
```
var workspace = Blockly.inject('blocklyDiv',
      {toolbox: document.getElementById('toolbox')});
```
https://developers.google.com/blockly/guides/configure/web/toolbox

Is there any method that transforms toolbox.xml into valid toolboxCategories I did miss?

**Comment by nbudin** [comment]
No, there is no such method - I'd been doing it by hand.  If you want to write such a method, I would be happy to accept a PR.

**Comment by Macilias** [comment]
I assume everything what is related for doing the transition can be found in BlocklyToolboxCategory.jsx, right?

**Comment by nbudin** [comment]
Yes, the propTypes in there more or less match the XML schema.

**Comment by Macilias** [comment]
than I´ll probably implement this method.

**Comment by Macilias** [comment]
please take a look at: https://github.com/patientslikeme/react-blockly-component/pull/26 
It works but could be without doubt implemented more elegantly than this. Basically the extraction of categories and transformation of fields from array into (for what ever reason) map was necessary.
