### ISSUE TITLE
Failed to compile on create-react-app build

### ISSUE THREAD

**Issue by andywindowsmac** [patientslikeme/react-blockly-component#28]
Failed to minify the code from this file

![image](https://user-images.githubusercontent.com/17358112/47494590-dcad8c80-d873-11e8-847e-e41447705cf3.png)

"react-blockly-component": "^3.1.1",
"react": "^16.4.0",
"react-dom": "^16.4.0",
"react-scripts": "1.1.4",

**Comment by nbudin** [comment]
@andywindowsmac Could you post a link to your code so I can try to reproduce the issue and debug it locally?

**Comment by andywindowsmac** [comment]
> @andywindowsmac Could you post a link to your code so I can try to reproduce the issue and debug it locally?

I already fix the issue, just update "react-scripts": "2.0.3"
