### ISSUE TITLE
Blockly is not defined

### ISSUE THREAD

**Issue by MMMystery** [patientslikeme/react-blockly-component#29]
![image](https://user-images.githubusercontent.com/7261385/48191830-1eb0f500-e381-11e8-8d78-80f6265a01c0.png)

**Comment by nbudin** [comment]
Because Blockly is not webpack-friendly, you have to include Blockly's JavaScript in a separate `<script>` tag above your main Webpack bundle.  See https://github.com/patientslikeme/react-blockly-component/blob/master/public/index.html for an example of how to do this.
