### ISSUE TITLE
Generate Php, Javascript code

### ISSUE THREAD

**Issue by mehdijjz** [patientslikeme/react-blockly-component#5]
How do I generate php , javascript or any other supported languages ?

**Comment by R9KT4** [comment]
Hi, I share the same concern.
Thanks btw, great component!

**Comment by nbudin** [comment]
Hey folks!  Sorry for not seeing this until now.

We don't use this component ourselves anymore, so I'm not sure I'll be able to make code modifications myself.  However, I think this could be done by adding a `workspaceDidChange` function property, similar to the existing `xmlDidChange` property, that passes the workspace object.  You could then attach a function similar to the one in the Blockly documentation under realtime generation of code: https://developers.google.com/blockly/guides/configure/web/code-generators#realtime_generation

If anyone has the time to make a PR adding a `workspaceDidChange` function property, I would be glad to merge and release.  Thanks!
